service: sre

provider:
  name: aws
  region: eu-west-3
  
  vpc:
   securityGroupIds:
    - lll
   subnetIds:
    - eee
    - ddd
    - yyy
  environment:
    REDIS_HOST: xxx

functions:
  sre:
    handler: canary.handler